### PR TITLE
Add ARMv8, PPC64, SystemZ Travis

### PR DESCRIPTION
**Pull request by XVilka**
**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Is it possible to build without Cutter counterparts? Because seems there is no Qt for these architectures.

**Comment by thestr4ng3r** [comment]
yes

**Comment by XVilka** [comment]
Ok, now it builds successfully on multiple platforms but many tests are broken.

**Comment by thestr4ng3r** [comment]
Didn't look too closely but the thest are broken because the plugin isn't loaded at all.
Also x86 can be removed completely from travis since it is now tested in GHA.

**Comment by XVilka** [comment]
Yes, I know it should be removed. I kept it as a reference for now, to judge that it should work.

**Comment by XVilka** [comment]
@thestr4ng3r it's ready to be merged now. ARMv8 build passes fine, S390 and PPC are marked as "allowed failures" like in Rizin, to be able to improve the support later.

**Pull request merged**
